# Generated by Django 4.2.23 on 2025-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.AddField(
            model_name='facture',
            name='commandes',
            field=models.ManyToManyField(blank=True, to='factures.commande'),
        ),
    ]
