# Generated by Django 4.2.23 on 2025-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_remove_facture_commande_facture_commandes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(blank=True, to='factures.produit'),
        ),
    ]
