# Generated by Django 4.2.23 on 2025-07-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_commande_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='factures.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factures.produit')),
            ],
        ),
    ]
